apiVersion: apps/v1
kind: Deployment
metadata:
  name: patiwat-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patiwat-backend
  template:
    metadata:
      labels:
        app: patiwat-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: patiwat-backend
          image: ghcr.io/teehit101/guestbook-backend:65d18981bd1958ff92cd06b74660d821d7e77a94

          ports:
            - containerPort: 8080
          env:
            # PostgreSQL Environment Variables
            - name: DB_HOST
              value: "patiwat-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: DB_USER
            # Redis Environment Variables
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: "patiwat-redis"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
