apiVersion: apps/v1
kind: Deployment
metadata:
  name: patiwat-frontend
  labels:
    app: patiwat-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: patiwat-frontend
  template:
    metadata:
      labels:
        app: patiwat-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: patiwat-frontend

          image: ghcr.io/teehit101/guestbook-frontend:65d18981bd1958ff92cd06b74660d821d7e77a94
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: API_BASE_URL
              value: "http://patiwat-backend:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
