apiVersion: apps/v1
kind: Deployment
metadata:
  name: patiwat-frontend
  labels:
    app: patiwat-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patiwat-frontend
  template:
    metadata:
      labels:
        app: patiwat-frontend
    spec:
      containers:
        - name: patiwat-frontend
          image: ghcr.io/teehit101/guestbook-frontend:8f21067f8d02f9bd5ed98239fd202e04cdb283a7
          ports:
            - containerPort: 8080
          env:
            - name: API_BASE_URL
              value: "http://backend:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
