apiVersion: apps/v1
kind: Deployment
metadata:
  name: patiwat-frontend
  labels:
    app: patiwat-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: patiwat-frontend
  template:
    metadata:
      labels:
        app: patiwat-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: patiwat-frontend

          image: ghcr.io/teehit101/guestbook-frontend:f6fbdfcd082dedbe5682c200eb0de74bf0412f63
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: API_BASE_URL
              value: "http://patiwat-backend:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
