apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patiwat-postgres-storge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
